language: node_js

notifications:
  webhooks:
    - $SLACK_HOOK

node_js:
  - "node"

script:
  - npm test
  - npm install codecov -g

after_success:
  - npm run coverage
  - codecov

services:
  - docker

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master