language: node_js

node_js:
  - "node"

script:
  - npm test

after_success: npm run coverage

services:
  - docker

before_install:
  - docker build -t ainz/urigin .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master