language: node_js

notifications:
  webhooks:
    - $SLACK_HOOK

node_js:
  - "node"

script:
  - npm test

after_success: npm run coverage

services:
  - docker

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master