openapi: "3.0.0"
info:
  version: 1.0.0
  title: Urigin
  license:
    name: MIT
servers:
  - url: http://localhost:3000/v1
paths:
  /users/login:
    post:
      summary: Get your authentification token
      operationId: login
      requestBody:
        description: User identification
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
          text/plain:
            schema:
              type: string
      tags:
        - users
      responses:
        '200':
          description: connexion token
        '400':
          description: error with the body
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UriginError"
        '500':
          description: error in the server side
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UriginError"
  /users:
    get:
      summary: Get all user
      operationId: getusers
      tags:
        - users
      security:
        - bearerAuth: [user, creator, moderator, admin]
      responses:
        '200':
          description: List users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UriginError"
        '403':
          description: Forbidden, you don't have enough rights
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UriginError"
        '498':
          description: Your token is invalid or expired
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UriginError"
    post:
      summary: Create new user
      operationId: createUsers
      tags:
        - users
      requestBody:
        description: new user
        required: true
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: your user was created
        '400':
          description: error with the body
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UriginError"
        '500':
          description: error in the server side
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UriginError"
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  schemas:
    UriginError:
      required:
        - description
      properties:
        description:
          type: string
    User:
      properties:
        id:
          # Returned by GET, not used in POST/PUT/PATCH
          type: integer
          readOnly: true
        email:
          # Used in POST/PUT/PATCH, not returned by GET
          type: string
          writeOnly: true
        username:
          type: string
        role:
          type: integer
          description: Only if your are admin
        password:
          # Used in POST/PUT/PATCH, not returned by GET
          type: string
          writeOnly: true