showConsole: true
layout:
  scope: section
theme:
  colors:
    text:
      primary: '#333333'
  typography:
    headings:
      fontFamily: 'Roboto'
    fontFamily: 'Roboto, Verdana, Geneva, sans-serif'
    fontSize: '14px'
    code:
      fontFamily: '"Courier New",monospace'
      tokens:
        'token.property':
          color: "#aofbaa"
        string:
          color: "#aofbaa"
    rightPanelHeading:
      color: white
  rightPanel:
    backgroundColor: "#263238"
  links:
    color: "#6CC496"

redocURL: https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js
redocExport: RedocPro
unstable_externalDescription: description.md